networks:
  mesh:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24

services:
  consul1:
    image: hashicorp/consul:1.22
    container_name: consul1
    command: consul agent -server -node=server1 -bootstrap-expect=5 -data-dir=/consul/data -client=0.0.0.0 -log-level=warn -ui -config-dir=/consul/config -retry-join=consul2 -retry-join=consul3 -retry-join=consul4 -retry-join=consul5
    ports:
      - "8500:8500"
    volumes:
      - ./consul:/consul/config
    networks:
      mesh:
        ipv4_address: 10.0.0.2
    healthcheck:
      test: [ "CMD", "consul", "members" ]
      interval: 2s
      timeout: 3s
      retries: 15

  consul2:
    image: hashicorp/consul:1.22
    container_name: consul2
    command: consul agent -server -node=server2 -bootstrap-expect=5 -data-dir=/consul/data -client=0.0.0.0 -log-level=warn -config-dir=/consul/config -retry-join=consul1 -retry-join=consul3 -retry-join=consul4 -retry-join=consul5
    volumes:
      - ./consul:/consul/config
    networks:
      mesh:
        ipv4_address: 10.0.0.3
    healthcheck:
      test: [ "CMD", "consul", "members" ]
      interval: 2s
      timeout: 3s
      retries: 15

  consul3:
    image: hashicorp/consul:1.22
    container_name: consul3
    command: consul agent -server -node=server3 -bootstrap-expect=5 -data-dir=/consul/data -client=0.0.0.0 -log-level=warn -config-dir=/consul/config -retry-join=consul1 -retry-join=consul2 -retry-join=consul4 -retry-join=consul5
    volumes:
      - ./consul:/consul/config
    networks:
      mesh:
        ipv4_address: 10.0.0.4
    healthcheck:
      test: [ "CMD", "consul", "members" ]
      interval: 2s
      timeout: 3s
      retries: 15

  consul4:
    image: hashicorp/consul:1.22
    container_name: consul4
    command: consul agent -server -node=server4 -bootstrap-expect=5 -data-dir=/consul/data -client=0.0.0.0 -log-level=warn -config-dir=/consul/config -retry-join=consul1 -retry-join=consul2 -retry-join=consul3 -retry-join=consul5
    volumes:
      - ./consul:/consul/config
    networks:
      mesh:
        ipv4_address: 10.0.0.5
    healthcheck:
      test: [ "CMD", "consul", "members" ]
      interval: 2s
      timeout: 3s
      retries: 15

  consul5:
    image: hashicorp/consul:1.22
    container_name: consul5
    command: consul agent -server -node=server5 -bootstrap-expect=5 -data-dir=/consul/data -client=0.0.0.0 -log-level=warn -config-dir=/consul/config -retry-join=consul1 -retry-join=consul2 -retry-join=consul3 -retry-join=consul4
    volumes:
      - ./consul:/consul/config
    networks:
      mesh:
        ipv4_address: 10.0.0.6
    healthcheck:
      test: [ "CMD", "consul", "members" ]
      interval: 2s
      timeout: 3s
      retries: 15

  service-a-sidecar:
    container_name: service-a-sidecar
    image: hashicorp/consul:1.22
    network_mode: "service:service-a"
    restart: on-failure
    command: sh /sidecar/sidecar.sh service-a
    volumes:
      - ./sidecar/:/sidecar/
    depends_on:
      consul1:
        condition: service_healthy
      consul2:
        condition: service_healthy
      consul3:
        condition: service_healthy
      consul4:
        condition: service_healthy
      consul5:
        condition: service_healthy

  service-b-sidecar:
    container_name: service-b-sidecar
    image: hashicorp/consul:1.22
    network_mode: "service:service-b"
    restart: on-failure
    command: sh /sidecar/sidecar.sh service-b
    volumes:
      - ./sidecar/:/sidecar/
    depends_on:
      consul1:
        condition: service_healthy
      consul2:
        condition: service_healthy
      consul3:
        condition: service_healthy
      consul4:
        condition: service_healthy
      consul5:
        condition: service_healthy

  service-a:
    container_name: service-a
    build:
      dockerfile: Dockerfile.services
      target: service-a
    # command: go run main.go
    networks:
      - mesh
    depends_on:
      consul1:
        condition: service_healthy
      consul2:
        condition: service_healthy
      consul3:
        condition: service_healthy
      consul4:
        condition: service_healthy
      consul5:
        condition: service_healthy

  service-b:
    container_name: service-b
    build:
      dockerfile: Dockerfile.services
      target: service-b
    # command: go run main.go
    networks:
      - mesh
    depends_on:
      consul1:
        condition: service_healthy
      consul2:
        condition: service_healthy
      consul3:
        condition: service_healthy
      consul4:
        condition: service_healthy
      consul5:
        condition: service_healthy
